# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2a28a0f1217de4554c3a43cc7a8c0a5713fa3d6a84b01cc6e19addcb5eda489fbe8e1561e2858fedb727f68fa503b3c8803f18afb728a2ed3dfca9496185bd6

test:
  secret_key_base: ac7ca304a1bd2b22f7dc208ac874d0efd8c886b3aa874a5e21ab6d39808f743c92ac0178da17a8d2dc865f9da6a3d5dcc8b7b2aaf48de5cf2dc532c6a1ea2ad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
