# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f10b6689792fdf08eb5bd456f649ef096ef406553ec40917ada39d381855ccb29ec2bcec24d53e988b631f7ba28154763b78815beb76f0e6add434a68d28179a

test:
  secret_key_base: b42443e9fd716cee56a777376a2c10e684eccc5ea2a1b3e8da5d7e605b98b47116b749d4182d7aeac3e8b8b4c7794e472ee25232c4eb0afc56bf68a95649a212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
