# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7a71f27f166f6816ca679cdfd15604809d2d22904ebc69f9ab0091b6c096f4287ab1ef820199e96cc332637b127981fb591bdd26aa2db330af0da57cee6755e

test:
  secret_key_base: adbe1bfc44b6ebfb2b77738c1db1f274689ea645fb63b68d3a08827fa4d0f735d671be07e947169232212ca694d38458dd62571dd51c98f440370f2994e7efc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
