# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e7504a7b150744695bb06f73bed5cca70bef3221e03bbe547d434c1ef5fc257e6ffed09d628d61360f5d0c9ead9858947989828eca847134a8282c894d2dc1b

test:
  secret_key_base: ff9f955165a7862c842f38010dd3ff797500c6b8ab17da8e61329ca0e8a1de64e3c5153af427da65e37c385dae1b698f19a2212c349377899fbc5c6e3f0456ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
