# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34a896a998f53763d949af438b03f0e827f0e4ce5ec8a719f8bde5720cbb6c555334c99b6a226773b1661d61fc0f48ef77d81ca8ad9b755e8e69f79c750feb41

test:
  secret_key_base: c5f9db854bd0ccedd35d49502ad4f8f04aa923135a7fb6a9643833eefb001d5108d933764c5f29e1c83108e4cee0e719c0e81d5c43e0dfefc730deeeca1c08a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
